name: firebase_admin
description: A port of the Firebase admin sdk to pure, idiomatic Dart code
version: 0.3.0-dev.5
homepage: https://github.com/appsup-dart/firebase_admin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clock: ^1.1.0
  x509: ^0.2.2
  jose: ^0.3.2
  dotenv: ^4.0.0
  openid_client: ^0.4.3
  firebase_dart: ^1.0.10
  path: ^1.8.0
  meta: ^1.4.0
  http: '>=0.13.0 <2.0.0'
  crypto_keys: ^0.3.0
  collection: ^1.15.0
  gcloud: ^0.8.0
  firebaseapis: ^0.1.2
  snapshot: ^0.2.5
  _discoveryapis_commons: ^1.0.4
  googleapis: ^9.2.0

dev_dependencies:
  test: ^1.17.8
  fake_async: ^1.2.0
  lints: ^2.0.0
  mockito: ^5.0.10

false_secrets:
 - /lib/src/testing.dart 
