name: firebase_admin
description: A port of the Firebase admin sdk to pure, idiomatic Dart code
version: 0.1.2+1
homepage: https://github.com/appsup-dart/firebase_admin

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  clock: ^1.0.0
  x509: ^0.1.0
  jose: '>=0.1.2 <0.3.0'
  dotenv: ^2.0.0
  openid_client: ^0.2.5
  firebase_dart: ^0.7.15+3
  path: ^1.6.4
  meta: ^1.1.6
  http: ^0.12.0
  crypto_keys: ^0.1.0
  collection: ^1.14.11
  gcloud: '>=0.6.3 <0.8.0'

dev_dependencies:
  test: ^1.0.0
  fake_async: ^1.0.0
  pedantic: ^1.9.0
  mockito: ^4.1.1
