name: firebase_admin
description: A port of the Firebase admin sdk to pure, idiomatic Dart code
version: 0.2.0-dev.2
homepage: https://github.com/appsup-dart/firebase_admin

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  clock: ^1.1.0
  x509: ^0.2.2
  jose: ^0.3.2
  dotenv: ^3.0.0
  openid_client: ^0.4.1
  firebase_dart: ^1.0.0-dev.45
  path: ^1.8.0
  meta: ^1.4.0
  http: ^0.13.0
  crypto_keys: ^0.3.0
  collection: ^1.15.0
  gcloud: ^0.8.0

dev_dependencies:
  test: ^1.17.8
  fake_async: ^1.2.0
  pedantic: ^1.11.1
  mockito: ^5.0.10
